language: R
cache:
  - packages
  - ccache
latex: false
sudo: required
os: linux
dist: xenial

r:
  - release
  - oldrel

before_install:
#  Add GDAL, GEOS, proj, and units2 dependencies
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

r_binary_packages:
  - sp
  - rgdal
  - rgeos
  - sf
  - dplyr
  - units
  - leaflet
  - markdown
  - readr
  - rmarkdown
  - stringi
  - tidyr
  - ggplot2
  - geojsonsf
  - httr
  - rlang
  - jsonlite
  - digest
